source 'https://rubygems.org'

gem 'rails', '4.2.0'
gem 'pg'
gem 'sass-rails', '>= 3.2'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'haml', '~> 4.0.6'
gem 'paperclip', '~> 4.2.1'
gem 'simple_form', '~> 3.1.0'
gem 'bootstrap-sass', '~> 3.3.6'
gem 'devise'
gem 'acts_as_votable', '~> 0.10.0'
gem 'kaminari', '~> 0.16.3'
gem 'jquery-turbolinks'
gem 'rails_12factor', group: :production
gem 'best_in_place', '~> 3.0.1'
gem 'momentjs-rails', '>= 2.9.0'
gem 'bootstrap3-datetimepicker-rails', '~> 4.17.43'
gem 'jquery-dynatable-rails'
gem "twitter-bootstrap-rails"
gem 'font-awesome-rails', '~> 4.3'
gem 'frontend-generators'
gem 'fullcalendar-rails'
gem 'aws-sdk', '~> 2'